import Main from '@/components/Main'
import About from '@/components/About'
import Head from 'next/head'
import Skills from '@/components/Skills'
import Projects from '@/components/Projects'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main/>
      <About/>
      <Skills/>
      <Projects/>
      
    </>
  )
}
